### ISSUE TITLE
just suddenly stopped working

### ISSUE THREAD

**Issue by JaneCoder** [magbicaleman/open-in-browser#45] opened 2017-05-17 14:45 UTC
I'm on atom 1.17.0 x 64. This package has been great, but has suddenly just stopped working. I right click on an html file and select 'open in browser' and nothing happens. There is no error message or any feedback either. I updated all my packages, but this did not fix the issue.

**Comment by BluePawDev** [comment] 2017-05-17 21:02
Same problem...verbatim.

**Comment by magbicaleman** [comment] 2017-05-18 11:46
What OS are you guys on?

**Comment by BluePawDev** [comment] 2017-05-18 13:09
macOS Sierra v10.12.4 (64-bit)
Prior to _open-in-browser_ (v0.5.0) ceasing to work I had not:

- installed any OS updates/patches/fixes;
- changed any system settings, nor;
- updated any applications

It very strangely just seemed to stop working and I cannot think of any outside influence that would have been the cause. I'm sure there is a reasonable cause and effect; just none that I can see.

Something that I had noticed several weeks ago is that in Atom, under settings, when I select Updates it generates the error _Fetching outdated packages and themes failed_. It is possible it could be related, however _open-in-browser_ had been working without any noticeable issue several weeks even after I began seeing the update error.

**Comment by JaneCoder** [comment] 2017-05-18 15:03
OS X El Capitan 10.11.6

**Comment by jacobbodkin** [comment] 2017-05-18 15:50
Same issue exactly. 

OS Sierra 10.12.5, Atom 1.17.0

**Comment by BluePawDev** [comment] 2017-05-18 15:51
My default browser is: Chrome v58.0.3029.110 (64-bit)

**Comment by jacobbodkin** [comment] 2017-05-18 15:53
@BluePawDev what version of Atom are you running? I'm thinking it has to do with the new release

**Comment by BluePawDev** [comment] 2017-05-18 15:55
1.17.0 (64-bit)

**Comment by BluePawDev** [comment] 2017-05-18 15:55
BTW, I was able to clear the update issue I was having--doesn't seem to be related or have any impact either way.

**Comment by TimBiden** [comment] 2017-05-24 00:16
Same scenario. Exactly. Just started today.

- MacOS Sierra - 10.12.4
- Atom - 1.17.0 x 64
- Chrome - Version 58.0.3029.110 (64-bit)

**Comment by gtodd876** [comment] 2017-05-24 11:47
I just installed this package and it does not work. Nothing happens after right click and select open in browser. Chrome is my default browser.

- MacOS Sierra 10.12.4
- Atom - 1.17.0 x64
- Chrome - Version 58.0.3029.110 (64-bit)

**Comment by magbicaleman** [comment] 2017-05-26 05:13
Pushed out a new version, please let me know if this has resolved the issue
- open-in-browser@v0.5.1

**Comment by maccer83** [comment] 2017-05-26 06:49
I also noticed this lately with 0.5.0. Just installed 0.5.1 but still nothing happens when I right-click on a file in the project tree and select "open in browser", or choose the command from the Packages menu for that matter.
MacOS Sierra 10.12.5
Atom 1.17.2 x64 (just updated from 1.17.0)
Safari 10.1.1
System language: Swedish

**Comment by objectkit** [comment] 2017-05-26 09:26
Unfortunately 0.5.1 didn't solve the problem. macOS Sierra / Safari. Problem began after updating to Atom 1.17.0.

**Comment by gtodd876** [comment] 2017-05-26 12:15
It did not solve the problem for me.

I noticed my cursor will jump to the beginning of the file but that's the only behavior I notice when I run the command.

**Comment by BluePawDev** [comment] 2017-05-26 13:40
Same result as @maccer83:
Right-click and selecting _Open in Browser_ from the context menu in the project tree does _not_ work, but a right-click and selecting _Open in Browser_ from the context menu within the editing area works.
I'll take that over nothing.

**Comment by TimBiden** [comment] 2017-05-26 14:58
Same as @BluePawDev.

Nothing happens when CTRL-clicking in the tree view. CTRL-clicking in the editor of the open file that you want to run in the browser does work.

**Comment by JaneCoder** [comment] 2017-05-26 18:50
Good catch, it is only not working with tree view.
And shift-cmd-Q also works if you click on the file.

**Comment by gtodd876** [comment] 2017-05-26 19:08
![screen shot 2017-05-26 at 2 55 44 pm](https://cloud.githubusercontent.com/assets/28220658/26508644/81fd7a8a-4223-11e7-864b-1b164ce69006.png)
![screen shot 2017-05-26 at 2 55 53 pm](https://cloud.githubusercontent.com/assets/28220658/26508645/8200bfec-4223-11e7-848d-fc592d127b58.png)

I just noticed that the key command to log out of my user account is the same as the default key command for open-in-browser. I was wondering if this has something to do with it. I tried looking in system preferences/keyboard/shortcuts to disable 'log out ("username")' but it's not listed there. I did an override of that global key command under *Application Shortcuts* create your own shortcut for *Log Out <Your Username>...* So now that key command is different but it still does not work if I try to right click, open in browser. If I now use the key command shift+command+Q in atom it only moves my cursor to the beginning of the file.

**Comment by magbicaleman** [comment] 2017-05-27 19:19
If you're experiencing open through the tree pane, are you using the default tree pane or another tree pane? For example are you using `nuclide-file-tree`

**Comment by magbicaleman** [comment] 2017-05-27 20:50
Published a new patch `0.5.2` that should address the context menu "Open in Browser" issue.

**Comment by maccer83** [comment] 2017-05-28 10:50
Thanks, 0.5.2 seems to have solved the problem for me – right-clicking in the tree view works again! I use the standard tree pane.

**Comment by gtodd876** [comment] 2017-05-28 11:15
Yesterday I experienced some weird behavior. I tried using open-in-browser from the command palette and apple Xcode tried to start up. Now that I have updated to 0.5.2 that doesn't happen anymore but initiating command for open-in-browser just moves the focus to the editor window and places the cursor at 1,1. 
![oib](https://cloud.githubusercontent.com/assets/28220658/26528259/76a199b6-4375-11e7-824f-5251a16ba1f9.gif)

**Comment by BluePawDev** [comment] 2017-05-30 13:22
@magbicaleman:
v0.5.2 look to have done the trick! Thank you!
BTW, I was/am using the default Atom tree view.
Thank you again for your work on the fix. I'm glad to have your package back and working again!

**Comment by magbicaleman** [comment] 2017-05-30 14:11
@gtodd876 I'm going to close this issue, my apologies for the inconvenience but may you open a new issues with what you're experiencing. Also thank you very much for adding a gif video, that helps a lot for me.

**Closed by magbicaleman** 2017-05-30 14:11 UTC
Labels: bug

**Comment by gtodd876** [comment] 2017-05-30 14:22
No problem, totally understand it's an issue specific specific to my system. I'll open a new issue.
